### ISSUE TITLE
 No module named 'nengo.utils.compat'

### ISSUE THREAD

**Issue by steroal** [abr/neurorobotics-2020#21]
Dear Pawel/Travis,
I want to do some experiments with nengo and reinforcement learning.
I followed the readme file to try running the sample.
The following error occurs:
Traceback (most recent call last):
  File "rover.py", line 16, in <module>
    from rover_vision import RoverVision
  File "G:\robot\neurorobotics-2020\rover_demo\rover_vision.py", line 29, in <module>
    import nengo_dl
  File "F:\anaconda\envs\mujoco\lib\site-packages\nengo_dl\__init__.py", line 42, in <module>
    from nengo_dl.simulator import Simulator  # noqa: F401
  File "F:\anaconda\envs\mujoco\lib\site-packages\nengo_dl\simulator.py", line 19, in <module>
    from nengo_dl.tensor_graph import TensorGraph
  File "F:\anaconda\envs\mujoco\lib\site-packages\nengo_dl\tensor_graph.py", line 14, in <module>
    from nengo_dl import builder, graph_optimizer, signals, utils, tensor_node
  File "F:\anaconda\envs\mujoco\lib\site-packages\nengo_dl\graph_optimizer.py", line 9, in <module>
    from nengo.utils.compat import iteritems
ModuleNotFoundError: No module named 'nengo.utils.compat'

nengo officially says that i need to install nengo==2.8, but nengo-loihi requires Nengo to be >= 3.0
How can I overcome this difficulty?

**Comment by steroal** [comment]
ps: i do thosething on win10.
